# Site settings
title: Sean's blog
email: sean.johnst[at]gmail.com
description: > # this means to ignore newlines until "baseurl:"
  In this blog, I'll write about my journey from bench biochemist
  to software developer... starting from scratch.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://seanjohnite.github.io" # the base hostname & protocol for your site
twitter_username: seanjohnite
github_username:  seanjohnite

# Build settings
markdown: kramdown
